services:
    Pdir\SocialFeedBundle\Importer\InstagramClient:
        public: true
        arguments:
            - "@Pdir\\SocialFeedBundle\\Importer\\InstagramRequestCache"
            - "@contao.framework"
            - "@?logger"
        tags:
            - { name: monolog.logger, channel: contao }

    Pdir\SocialFeedBundle\Importer\InstagramRequestCache:
        public: true
        arguments:
            - "@filesystem"
            - ~ # cache_ttl to be set in extension class
            - "%kernel.project_dir%"

    Pdir\SocialFeedBundle\Controller\InstagramController:
        public: true
        arguments:
            - "@Pdir\\SocialFeedBundle\\Importer\\InstagramClient"
            - "@database_connection"
            - "@router"
            - "@session"
            - "@security.token_storage"

    Pdir\SocialFeedBundle\Controller\LinkedinController:
        public: true
        arguments:
            - "@database_connection"
            - "@router"
            - "@session"

    Pdir\SocialFeedBundle\Controller\FacebookController:
        public: true
        arguments:
            - "@database_connection"
            - "@router"
            - "@session"
            - "@security.token_storage"

    Pdir\SocialFeedBundle\EventListener\SocialFeedListener:
        public: true
        arguments:
            - "@router"
            - "@session"

    pdir_social_feed_moderate.controller:
        class: Pdir\SocialFeedBundle\Controller\ModerateController
        public: true
        arguments:
            - "@contao.framework"
            - "@request_stack"
